apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false
  extra_lua_path: "/opt/?.lua"
  enable_control: true
  allow_embedding: true
  control:
    ip: "0.0.0.0"
    port: 9092
  security:
      access_control_allow_origin: "*"
      access_control_allow_credentials: true  # Support using custom CORS configuration
      access_control_allow_headers: "Authorization"
      access_control_allow_methods: "*"
      x_frame_options: "deny"
      content_security_policy: "default-src '127.0.0.1'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; frame-src 127.0.0.1:3000" 

  # Enable Prometheus plugin for metrics exposure
  enable_prometheus: true

  # Prometheus metrics exposure port
  prometheus:
    port: 9091                  # Exposing metrics on port 9091
    format: "prometheus"

deployment:
  admin:
    allow_admin:               # https://nginx.org/en/docs/http/ngx_http_access_module.html#allow
      - 0.0.0.0/0              # We need to restrict IP access rules for security. 0.0.0.0/0 is for test.

    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin              # admin: manage all configuration data

      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer

  # etcd:
  #   host:                        # It's possible to define multiple etcd hosts addresses of the same etcd cluster.
  #     - "http://13.202.148.227:2379"        # Multiple etcd address
  #   prefix: "/apisix"            # APISIX configurations prefix
  #   timeout: 30 
  etcd:
    host:                        # It's possible to define multiple etcd hosts addresses of the same etcd cluster.
      - "http://13.233.56.23:2379"        # Multiple etcd address
    prefix: "/apisix"            # APISIX configurations prefix
    timeout: 30  

logger:
  level: "info"
  file: "/usr/local/apisix/logs/error.log"

log:
  error_log: /var/log/apisix/error.log
  access_log: /var/log/apisix/access.log
# nginx_config:
#   error_log: logs/error.log info  # Change "warn" to "info" to allow logging


plugin_attr:
  prometheus:
    export_uri: /apisix/prometheus/metrics
    export_addr:
      ip: "0.0.0.0"
      port: 9091
    metrics:                                 # Create extra labels from built-in variables.
      http_status:
        extra_labels:                        # Set the extra labels for http_status metrics.
          - upstream_addr: $upstream_addr    # Add an extra upstream_addr label with value being the NGINX variable $upstream_addr.
          - route_name: $route_name
          - client_ip: $remote_addr  
  redis_cache:
    redis_host: "13.233.56.23"
    redis_port: 6379
    redis_password: ""
    redis_db: 0
    cache_ttl: 6
    global_rules:
    enable: true
    
nginx_config:
  http:
    enable_buffering: true



plugins:
  - multi-auth
  - key-auth
  - pan_aadhar
  - consumer-restriction
  - proxy-rewrite
  - transform_response
  - cache_redis
  - AES-256
  - exit-on-auth-failure
  - body-transformer
  - pipeline-request
  - pipeline-requestv2
  - key
  - validate-phone
  - pan_validator
  - mobile_revoke
  - AES_256_GCM
  - limit-count
  - credit_bureau
  - mobile_revoke_validate
  - sort_transform_response
  - pan_tan_to_tds
  - tds_verification
  - pan_validator_true_billable
  - tan_validator
  - tds_amount_certi_validator
  - financial_year_validator
  - pan_advance_v1
  - panmaskaadhaar_enc
  - uan_passbook_result
  - uan_passbook_otp_gen
  - mobile_to_account_no
  - bodyTransformer
  - pan_basic_v1
  - transform_responseBAV
  - ifsc_validator
  - tb
  - response-key-remover
  - required-fields
  - crime_search_id_validator
  - crime_search_result
  - crime_search_id
  - efir_search_result
  - efir_search_id
  - efir_search_transform
  - matchType
  - efir_request_body
  - matchType
  - ECourt
  - dynamic_token_injector
  - mobile_validator_in_params
  - uan_v4_client_ref
  - mobile_pan_uan_validator
  - Efir
  - PAN_ADV_AES_265
  - upi_validator
  - digiLockerAuth
  - appendTokenInHeader
  - appendToken
  - msme
  - email_validator
  - required_keys_validator
  - email_advance
  - validate_non_empty_fields
  - consumer_allowlist
  - sorting
  - limit-count
  - updated_transform_response
  - consumer_api_quota_etcd
  - proxy_rewrite_body_req
  - response_code_mapper
  - status-code-mapper
  - api_chainMerge
  - dob_validator
  - passport_dob_validator
  - Ecourt_case_fuzzy_pipeline
  - Ecourt_fuzzy_1st_id_api
  - Ecourt_fuzzy_2nd_result_api
  - Ecourt_Matchtype
  - remove_static_input
  - proxy_rewrite_nested_json
  - dynamic_key_renamer
  - aadhaar_validator
  - customer_info_validator
  - gst_result_mapper
  - new_ifsc_validator
  - mobileToAlternativeAddChain
  - mobileToAlternativeNoChain
  - cin_validator
  - socialMedia
  - emailPhoneValid
  - socialMediaRequest
  - response-key-remover-nested-json
  - pan_mobile_validator
  - cache_redisSBIC
  - transform_responseSBIC
  - SortTransformResponse_New




