services:
  etcd:
    image: bitnami/etcd:3.5.11
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      - apisix_network

  apisix:
    image: "apache/apisix:latest"
    container_name: apisix
    depends_on:
      - etcd
    ports:
       - "9084:9080"   # APISIX HTTP port
       - "9444:9443"   # APISIX HTTPS port
       - "9184:9180"   # APISIX Admin API port
       - "9094:9091/tcp"
       - "9092:9092/tcp"
    environment:
       - ETCD_HOST=http://13.233.56.23:2379
    volumes:
        - ./apisix_config.yaml:/usr/local/apisix/conf/config.yaml:ro
        - ./plugins:/opt/apisix/plugins:ro
    networks:
        - apisix_network

  apisix_dashboard:
    image: "apache/apisix-dashboard:3.0.0-alpine"
    container_name: apisix_dashboard
    ports:
      - "9095:9000"
    environment:
      - APISIX_BASE_URL=http://13.233.56.23:9180
      - ETCD_HOST=http://13.233.56.23:2379
    volumes:
      - ./apisix_dashboard_config.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    networks:
      - apisix_network

  redis:
    image: redis:6.2
    container_name: redis
    ports:
       - "6378:6379"
    networks:
      - apisix_network

  

volumes:
  grafana_conf:
    driver: local
  etcd_data:
    driver: local

networks:
  apisix_network:
    driver: bridge



