services:
  etcd:
    image:  dhi.io/etcd:3-debian-dev
    container_name: etcd
    restart: always

    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ENABLE_V2=true
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379

    volumes:
      - ./etcd_data:/bitnami/etcd

    ports:
      - "2379:2379"
      - "2380:2380"

    networks:
      - etcd_network

networks:
  etcd_network:
    driver: bridge

